### ISSUE TITLE
General - Phone Numbers: Incorrect area code when clicking the phone number and fax

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Elan-Engineering#86] opened 2015-11-09 07:28 UTC
![image](https://cloud.githubusercontent.com/assets/13363508/11028101/73c41f76-86f6-11e5-8621-453d983ebf42.png)
![image](https://cloud.githubusercontent.com/assets/13363508/11028108/80ae70a6-86f6-11e5-88b0-da2ecc86ee31.png)

**Comment by asif-titan** [comment] 2015-11-16 04:55
It is not reproducible at my end i have tested it in ipad mini, Ipad Air and Ipod touch, the area code is showing correct.

**Comment by maehtitan** [comment] 2015-11-16 09:41
It is not correct on our end, showed it to my Team Manager and Team Leader, please strip down the parenthesis to all phone numbers. You can replicate the issue when clicking the phone numbers.

Thanks

**Comment by asif-titan** [comment] 2015-11-17 14:31
I have already stripped out all the parenthesis for the links, as you can see in the screenshot we are not getting any parenthesis in the number.
![e9e6ef66-077b-4ab6-93b1-bfc74aba5756-3](https://cloud.githubusercontent.com/assets/13450796/11213167/93ef9a30-8d60-11e5-8201-306daec4525b.jpg)

**Comment by maehtitan** [comment] 2015-11-19 05:23
It was fixed in your end but not in our end here right after clearing the cache.
![image](https://cloud.githubusercontent.com/assets/13363508/11262972/b6f0e744-8ec0-11e5-9126-49df33b99706.png)

**Comment by asif-titan** [comment] 2015-11-20 10:13
As per Salman's Talk with Bernard, Bernard has asked it to mark it as won't fix as the issue is related to the device.

**Closed** 2015-11-24 02:35 UTC
Labels: bug, wontfix
